#!/bin/bash

set -e pipefail

REVISION=master

wget http://resources.boardiq.co.uk.s3.amazonaws.com/ruby-2.2.2.tgz
tar zxvf ruby-2.2.2.tgz -C /app/

export PATH=/app/gems/bin:/app/ruby/bin:$PATH
export GEM_HOME=/app/gems

echo "Installing ngx_mruby"
git clone git://github.com/matsumoto-r/ngx_mruby.git

cd ngx_mruby
git submodule init
git submodule update

NGINX_CONFIG_OPT_ENV='--prefix=/app' sh build.sh

make install

tar czvf ngx_mruby.tgz conf/ html/ logs/ sbin/